use thiserror::Error;

/// Error lexing a source file.
#[derive(Debug, Error, PartialEq, Clone, Default)]
#[doc(hidden)]
pub enum LexError {
    /// Generic lex error.
    #[default]
    #[error("parser lex error")]
    Other,
}

/// Errors generated by the library.
#[derive(Debug, Error)]
pub enum Error {
    /// Unknown instruction.
    #[error("unknown instruction '{0}'")]
    UnknownInstruction(String),

    /// Script pragma must be first instruction.
    #[error("pragma declaration ($!) must be the first instruction")]
    PragmaFirst,

    /// Error generated by the io module.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Error generated parsing to an integer.
    #[error(transparent)]
    ParseInt(#[from] std::num::ParseIntError),

    /// Error generated by the pseudo-terminal library.
    #[error(transparent)]
    Rexpect(#[from] rexpect::error::Error),

    /// Error during lexing.
    #[error(transparent)]
    Lex(#[from] LexError),
}
